// Quiz-App-With-Svelte-and-Vue/svelte/src/App.svelte
<script lang="ts">
  import Header from "./components/Header.svelte";
  import Layout from "./components/Layout.svelte";
  import Question from "./components/Question.svelte";
  import { questions } from "./config";
  let question_index = 0;
  $: question = questions[question_index];
  const evaluation: boolean[] = [];

  function finish_question(e: CustomEvent<boolean>) {
    evaluation.push(e.detail);
    update_question();
  }

  function update_question() {
    if(question_index < questions.length - 1 ) {
      question_index++;
    }else {
      window.alert("FINISHED")
    }
  }
</script>

<Header />

<Layout>
  <Question on:finish={finish_question} {question}></Question>
</Layout>

// Quiz-App-With-Svelte-and-Vue/vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import Header from "./components/Header.vue";
import Question from "./components/Question.vue";
import Layout from "./components/Layout.vue";
import { questions } from "./config";
let question_index = ref(0);
const question = computed(() => questions[question_index.value]);

const evaluaion: boolean[] = [];

function finish_question(correct: boolean) {
  evaluaion.push(correct);
  update_question();
}

function update_question() {
  if (question_index.value < questions.length - 1) {
    question_index.value++;
  } else {
    window.alert("FINISHED");
  }
}
</script>

<template>
  <Header></Header>
  <Layout>
    <Question @finish="finish_question" :question="question"></Question>
  </Layout>
</template>
