// Quiz-App-With-Svelte-and-Vue/svelte/src/App.svelte
<script lang="ts">
  import Finished from "./components/Finished.svelte";
  import Header from "./components/Header.svelte";
  import Layout from "./components/Layout.svelte";
  import Progress from "./components/Progress.svelte";
  import Question from "./components/Question.svelte";
  import { questions } from "./config";
  let question_index = 0;
  $: question = questions[question_index];
  let evaluation: boolean[] = [];
  let finished = false;

  function finish_question(e: CustomEvent<boolean>) {
    evaluation.push(e.detail);
    update_question();
  }

  function update_question() {
    if (question_index < questions.length - 1) {
      question_index++;
    } else {
      finished = true;
    }
  }

  function restart() {
    question_index = 0;
    evaluation = [];
    finished = false;
  }
</script>

<Header />

<Layout>
  {#if !finished}
    <Progress count={questions.length} progress={question_index}></Progress>
    <Question on:finish={finish_question} {question}></Question>
  {:else}
    <Finished on:restart={restart} {evaluation}></Finished>
  {/if}
</Layout>

// Web/Quiz-App-With-Svelte-and-Vue/vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import Header from "./components/Header.vue";
import Question from "./components/Question.vue";
import Layout from "./components/Layout.vue";
import Finish from "./components/Finish.vue";
import Progress from "./components/Progress.vue";
import { questions } from "./config";
let question_index = ref(0);
let finished = ref(false);

const question = computed(() => questions[question_index.value]);

let evaluaion: boolean[] = [];

function finish_question(correct: boolean) {
  evaluaion.push(correct);
  update_question();
}

function update_question() {
  if (question_index.value < questions.length - 1) {
    question_index.value++;
  } else {
    finished.value = true;
  }
}

function restart() {
  question_index.value = 0;
  evaluaion = [];
  finished.value = false;
}
</script>

<template>
  <Header></Header>
  <Layout>
    <template v-if="!finished">
      <Progress :progress="question_index" :count="questions.length"></Progress>
      <Question @finish="finish_question" :question="question"></Question>
    </template>
    <Finish v-else :evaluaion="evaluaion" @restart="restart"></Finish>
  </Layout>
</template>
